storefront/core/urls.py
from . import views
from rest_framework.routers import DefaultRouter
from rest_framework_simplejwt.views import TokenObtainPairView
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.views.generic import TemplateView


app_name = 'core'

router = DefaultRouter()
router.register('SignUp', views.SignUpViewSet, basename='SignUp')
router.register('user', views.UserViewSet, basename='user')

# URLConf
urlpatterns = [
    path('', TemplateView.as_view(template_name='core/index.html'), name='Home'),
    #     path('signin/', views.SignIn, name='sign-in'),
    # path('profile/', views.my_profile, name='customer-profile')
    path('profile/', views.profile, name='profile'),
    path('profile/my_info/', views.my_info, name='my_info'),
    path('profile/my_orders/', views.my_orders, name='my_orders'),
    path('profile/change_details', views.change_details, name='change_details'),
    path('profile/change_email/', views.change_email, name='change_email'),
    path('profile/confirm_password/',
         views.confirm_password, name='confirm_password'),
    path('change_password/', views.change_password, name='change_password'),
    path('logout/', views.custom_logout, name='logout'),
    path('privacy_policy/', views.privacy_policy, name='privacy_policy'),
    path('accounts/login', views.CustomLoginView.as_view(), name='custom_login')
]

urlpatterns += router.urls

storefront/store/urls.py
from django.urls import path
from rest_framework_nested import routers
from . import views

app_name = 'store'


router = routers.DefaultRouter()
router.register('products', views.ProductViewSet, basename='products')
router.register('collections', views.CollectionViewSet)
router.register('carts', views.CartViewSet)
router.register('customers', views.CustomerViewSet, basename='customers')
router.register('orders', views.OrderViewSet, basename='orders')

products_router = routers.NestedDefaultRouter(
    router, 'products', lookup='product')
products_router.register('reviews', views.ReviewViewSet,
                         basename='product-reviews')
products_router.register(
    'images', views.ProductImageViewSet, basename='product-images')
orders_router = routers.NestedDefaultRouter(router, 'orders', lookup='order')

carts_router = routers.NestedDefaultRouter(router, 'carts', lookup='cart')
carts_router.register('items', views.CartItemViewSet, basename='cart-items')

# urlpatterns =[
#     path('products_page', views.\)
# ]

# URLConf
urlpatterns = router.urls + products_router.urls + carts_router.urls

urlpatterns += [

    path('products/products_page/',
         views.ProductViewSet.as_view({'get': 'products_page'}), name='products_page'),
    path('order_form', views.order_form_view, name='order_form'),
    path('order_success', views.order_success_page, name='order_success'),
    path('my_orders', views.my_orders, name='my_orders'),
    path('post_order', views.post_order, name='post_order'),
    path('search/', views.search, name='search'),
    path('search/suggestions/', views.search_suggestions,
         name='search_suggestions'),
]

storefront/storefront/urls.py
from django.urls import path
from django.http import JsonResponse
from django.contrib import admin
from django.urls import path, include
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static
from drf_yasg.views import get_schema_view
from drf_yasg import openapi
from rest_framework.permissions import AllowAny

schema_view = get_schema_view(
    openapi.Info(
        title="Storefront",
        default_version='v1',
        description="API description",
    ),
    public=True,
    permission_classes=(AllowAny,),
)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('__debug__/', include(debug_toolbar.urls)),
    path('', include('core.urls')),
    path('auth/', include('djoser.urls')),
    path('auth/', include('djoser.urls.jwt')),
    path('store/', include(('store.urls', 'store'), namespace='store')),
    path('swagger/', schema_view.with_ui('swagger',
         cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc',
         cache_timeout=0), name='schema-redoc'),
    path('accounts/', include('allauth.urls')),
    path('captcha/', include('captcha.urls')), 
    path('', include('django_prometheus.urls')),
    path('', include('pages.urls')),




]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

storefront/store/forms.py
from django.conf import settings
from django import forms
from django.forms.widgets import DateInput
from us.states import STATES


class OrderForm(forms.Form):
    phone = forms.CharField(max_length=255, label='Phone Number')
    # birth_date = forms.DateField(
    #     required=False,
    #     widget=DateInput(attrs={'type': 'date'}),
    #     label='Birth Date'
    # )
    street = forms.CharField(max_length=255, label='Street Address')
    city = forms.CharField(max_length=255, label='City')
    state = forms.CharField(max_length=20, label='State')
    # Generate state choices dynamically
    STATE_CHOICES = [(state.abbr, state.name) for state in STATES]

    state = forms.ChoiceField(
        choices=STATE_CHOICES,
        label='State',
        widget=forms.Select(attrs={
            'class': 'shadow appearance-none border rounded w-full py-2 px-3 leading-tight focus:outline-none focus:shadow-outline custom-select'
        })
    )

storefront/store/views.py
from django.http import HttpResponseRedirect, JsonResponse
from django.urls import reverse
from store.forms import OrderForm
from store.permissions import IsAdminOrReadOnly
from store.pagination import DefaultPagination
from django.shortcuts import redirect, render
from django.db.models.aggregates import Count
from django.shortcuts import get_object_or_404
from django_filters.rest_framework import DjangoFilterBackend
from rest_framework.decorators import action
from rest_framework.filters import SearchFilter, OrderingFilter
from django.contrib.auth.models import AnonymousUser
from rest_framework.mixins import CreateModelMixin, DestroyModelMixin, RetrieveModelMixin, UpdateModelMixin
from rest_framework.permissions import AllowAny, IsAdminUser, IsAuthenticated
from rest_framework.response import Response
from rest_framework.renderers import TemplateHTMLRenderer
from rest_framework.viewsets import ModelViewSet, GenericViewSet
from rest_framework import generics
from rest_framework import status
from .filters import ProductFilter
from django.contrib.auth.decorators import login_required
from .models import *
from .serializers import *
from django.core.mail import send_mail
from django.template.loader import render_to_string
from django.utils.html import strip_tags
from django.conf import settings
from django.core.mail import send_mail, BadHeaderError


class ProductViewSet(ModelViewSet, generics.RetrieveAPIView):
    queryset = Product.objects.prefetch_related('images').all()
    serializer_class = ProductSerializer
    filter_backends = [DjangoFilterBackend, SearchFilter, OrderingFilter]
    filterset_class = ProductFilter
    pagination_class = DefaultPagination
    permission_classes = [IsAdminOrReadOnly]
    search_fields = ['title', 'description']
    ordering_fields = ['unit_price', 'last_update']
    renderer_classes = [TemplateHTMLRenderer]
    # ^used to render customer templates

    def get_serializer_context(self):
        return {'request': self.request}

    def destroy(self, request, *args, **kwargs):
        if OrderItem.objects.filter(product_id=kwargs['pk']).count() > 0:
            return Response({'error': 'Product cannot be deleted because it is associated with an order item.'}, status=status.HTTP_405_METHOD_NOT_ALLOWED)

        return super().destroy(request, *args, **kwargs)

    @action(detail=False, methods=['get'])
    def products_page(self, request):
        products = self.get_queryset()

        return Response({'products': products}, template_name='store/products_page.html')

    def retrieve(self, request, *args, **kwargs):
        product = self.get_object()
        cart_id = request.session.get('cart_id')
        return Response({'product': product}, template_name='store/product_detail.html')


class ProductImageViewSet(ModelViewSet):
    serializer_class = ProductImageSerializer

    def get_queryset(self):
        return ProductImage.objects.filter(product_id=self.kwargs['product_pk'])

    def get_serializer_context(self):
        return {'product_id': self.kwargs['product_pk']}


class CollectionViewSet(ModelViewSet):
    queryset = Collection.objects.annotate(
        products_count=Count('products')).all()
    serializer_class = CollectionSerializer
    permission_classes = [IsAdminOrReadOnly]

    def destroy(self, request, *args, **kwargs):
        if Product.objects.filter(collection_id=kwargs['pk']):
            return Response({'error': 'Collection cannot be deleted because it includes one or more products.'}, status=status.HTTP_405_METHOD_NOT_ALLOWED)

        return super().destroy(request, *args, **kwargs)


class ReviewViewSet(ModelViewSet):
    serializer_class = ReviewSerializer

    def get_queryset(self):
        return Review.objects.filter(product_id=self.kwargs['product_pk'])

    def get_serializer_context(self):
        return {'product_id': self.kwargs['product_pk']}


class CartViewSet(CreateModelMixin,
                  RetrieveModelMixin,
                  DestroyModelMixin,
                  GenericViewSet):
    queryset = Cart.objects.prefetch_related('items__product').all()
    serializer_class = CartSerializer

    def create(self, request, *args, **kwargs):
        serializer = self.get_serializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        self.perform_create(serializer)
        headers = self.get_success_headers(serializer.data)

        cart_id = str(serializer.instance.id)
        request.session['cart_id'] = str(cart_id)

        # combine cart_id with serializer data
        response_data = serializer.data
        response_data['cart_id'] = cart_id

        return Response(response_data, status=status.HTTP_201_CREATED, headers=headers)

    def get_serializer_context(self):

        # This method returns a context dictionary to the serializer
        context = super().get_serializer_context()
        context.update({'request': self.request})
        # send request data over to extract image
        return context


class CartItemViewSet(ModelViewSet, generics.RetrieveAPIView):
    http_method_names = ['get', 'post', 'patch', 'delete']

    def get_serializer_class(self):
        if self.request.method == 'POST':
            return AddCartItemSerializer
        elif self.request.method == 'PATCH':
            return UpdateCartItemSerializer
        return CartItemSerializer

    def get_serializer_context(self):
        return {'cart_id': self.kwargs['cart_pk']}

    def get_queryset(self):
        return CartItem.objects \
            .filter(cart_id=self.kwargs['cart_pk']) \
            .select_related('product')

    @action(detail=True, methods=['post', 'patch', 'delete'], url_path='cart_item_update')
    def cart_item_update(self, request, pk=None, cart_pk=None):
        if request.data.get('_method') == 'PATCH':
            quantity = request.data.get('quantity')
            # This retrieves the CartItem instance based on the 'pk' from the URL.
            cart_item = self.get_object()
            cart_item.quantity = quantity
            cart_item.save()
            cart_url = reverse('store:cart-items-cart-page',
                               kwargs={'cart_pk': cart_pk})
            return HttpResponseRedirect(cart_url)

        elif request.data.get('_method') == 'DELETE':
            # This retrieves the CartItem instance based on the 'pk' from the URL.
            cart_item = self.get_object()
            cart_item.delete()
            cart_url = reverse('store:cart-items-cart-page',
                               kwargs={'cart_pk': cart_pk})
            return HttpResponseRedirect(cart_url)

    @action(detail=False, methods=['get'], renderer_classes=[TemplateHTMLRenderer],
            # permission_classes=([IsAuthenticated])
            )
    def checkout_page(self, request, pk=None, *args, **kwargs):
        # or however you store your token
        token = request.COOKIES.get('access_token')
        if not token:
            # Redirect to the sign-in page with the 'next' parameter
            return redirect(f'/accounts/login/?next={request.path}')

        form = OrderForm()

        cart_id = kwargs.get('cart_pk')
        if not cart_id:
            return Response({'error': 'Cart ID not found in session'}, status=status.HTTP_404_NOT_FOUND)

        try:
            cart = Cart.objects.get(pk=cart_id)
            cart_id = cart.id

            cart_items = cart.items.all()
            cart_total = sum(
                [item.product.unit_price * item.quantity for item in cart_items])
            context = {'form': form, 'cart': cart,
                       'cart_items': cart_items, 'cart_id': cart_id,
                       'total': cart_total}
            return Response(context, template_name='store/checkout_page.html')
        except Cart.DoesNotExist:
            return Response({'error': 'Cart not found'}, status=status.HTTP_404_NOT_FOUND)

    @action(detail=False, methods=['get'], renderer_classes=[TemplateHTMLRenderer])
    def cart_page(self, request, pk=None, **kwargs):
        cart_id = request.session.get('cart_id')

        if not cart_id:
            # No cart exists in the session, create a new cart
            cart = Cart.objects.create()
            cart_id = str(cart.id)
            request.session['cart_id'] = cart_id
        else:
            try:
                cart = Cart.objects.get(pk=cart_id)

            except Cart.DoesNotExist:
                # Cart does not exist in the database, create a new cart
                cart = Cart.objects.create()
                cart_id = str(cart.id)
                request.session['cart_id'] = cart_id

        cart_items = cart.items.all()
        cart_total = sum(
            [item.product.unit_price * item.quantity for item in cart_items])

        return Response({'cart': cart, 'cart_items': cart_items, 'cart_id': cart_id, 'total': cart_total}, template_name='store/cart_page.html')


class CustomerViewSet(ModelViewSet):
    queryset = Customer.objects.all()
    serializer_class = CustomerSerializer
    permission_classes = [IsAuthenticated]

    @action(detail=False, methods=['GET', 'PUT'])
    def me(self, request):

        user_id = self.request.user.id
        customer = Customer.objects.get(user_id=user_id)
        cart_id = request.session.get('cart_id')
        print(customer)
        if request.method == 'GET':
            serializer = CustomerSerializer(customer)
            # context = {'customer': customer, 'cart_id' : cart_id}
            customer_data = serializer.data
            customer_data['cart_id'] = cart_id
            print(customer_data)
            return Response(customer_data)

        elif request.method == 'PUT':
            serializer = CustomerSerializer(customer, data=request.data)
            serializer.is_valid(raise_exception=True)
            serializer.save()
            return Response(serializer.data)


class OrderViewSet(ModelViewSet):

storefront/store/templates/store/cart_page.html
{% load static %}

{% include 'store/header_with_tailwinds.html' %}

<div class="container mx-auto mt-8 px-4 sm:px-6 lg:px-8">
    <h1 class="text-3xl font-bold mb-6 text-center">Your Cart</h1>

    <!-- Go Back button -->
    <div class="text-center mb-4">
        <a href="{% url 'store:products_page' %}"
            class="bg-gray-500 hover:bg-gray-700 text-white font-bold py-2 px-4 rounded inline-block">Continue
            Shopping</a>
    </div>

    <!-- Cart items -->
    {% if cart_items %}
    <div class="bg-white p-4 rounded-lg shadow-md">
        <ul class="divide-y divide-gray-200">
            {% for item in cart_items %}
            <li
                class="py-6 flex flex-col sm:flex-row justify-between items-center bg-white rounded-lg shadow-md mb-4 p-4">
                <a href="{% url 'store:products-detail' item.product.id %}"
                    class="flex items-center space-x-4 w-full sm:w-auto">
                    <!-- Product image -->
                    {% with item.product.images.all|first as first_image %}
                    {% if first_image %}
                    <img class="w-20 h-20 object-cover rounded-lg" src="{{ first_image.image.url }}"
                        alt="{{ item.product.title }} Image">
                    {% else %}
                    <img class="w-20 h-20 object-cover rounded-lg" src="{% static 'default-product-image.jpg' %}"
                        alt="Default Image">
                    {% endif %}
                    {% endwith %}
                    <!-- Product details -->
                    <div class="text-left">
                        <h3 class="text-xl font-semibold text-gray-900">{{ item.product.title }}</h3>
                        <p class="text-gray-600">Price: ${{ item.product.unit_price }}</p>
                        <p class="text-gray-600">Quantity: {{ item.quantity }}</p>
                        <p class="text-gray-600">Total: ${{ item.product.unit_price|floatformat:2 }}</p>
                    </div>
                </a>
                <!-- Update and Delete buttons -->
                <div
                    class="flex flex-col sm:flex-row items-center space-x-0 sm:space-x-4 mt-4 sm:mt-0 w-full sm:w-auto">
                    <!-- Update quantity form -->
                    <form method="post"
                        action="{% url 'store:cart-items-cart-item-update' cart_pk=cart.id pk=item.id %}"
                        class="flex items-center">
                        {% csrf_token %}
                        <input type="hidden" name="_method" value="PATCH">
                        <div class="flex items-center">
                            <button type="button"
                                class="bg-gray-300 text-gray-700 px-3 py-1 rounded-l-md focus:outline-none"
                                onclick="updateQuantity(this, -1)">-</button>
                            <input type="number" name="quantity" min="1" value="{{ item.quantity }}"
                                class="w-16 px-2 py-1 border border-gray-300 text-gray-800 text-center no-arrows">
                            <button type="button"
                                class="bg-gray-300 text-gray-700 px-3 py-1 rounded-r-md focus:outline-none"
                                onclick="updateQuantity(this, 1)">+</button>
                        </div>
                        <button type="submit"
                            class="bg-blue-500 hover:bg-blue-700 text-white px-3 py-1 rounded-md ml-2">Update</button>
                    </form>
                    <!-- Delete item button -->
                    <form method="post"
                        action="{% url 'store:cart-items-cart-item-update' cart_pk=cart.id pk=item.id %}"
                        class="flex items-center mt-2 sm:mt-0">
                        {% csrf_token %}
                        <input type="hidden" name="_method" value="DELETE">
                        <button type="submit" class="text-red-500 hover:text-red-700 ml-0 sm:ml-4">Delete</button>
                    </form>
                </div>
            </li>
            {% endfor %}
        </ul>
        <!-- Subtotal -->
        <div class="mt-6 text-right">
            <h2 class="text-2xl font-semibold text-gray-900">Subtotal: ${{ total }}</h2>
        </div>
        <!-- Checkout button -->
        <div class="mt-6 text-right">
            <a href="{% url 'store:cart-items-checkout-page' cart_pk=cart.id %}"
                class="bg-white text-white-600 font-bold py-3 px-6 rounded shadow-md border-2 border-blue-600 hover:bg-blue-600 hover:text-white inline-block">Checkout</a>
        </div>
    </div>
    {% else %}
    <p class="text-center text-lg mt-8 text-gray-600">Your cart is empty. <a href="{% url 'store:products_page' %}"
            class="text-blue-500 hover:underline">Browse products</a> and add some to your cart!</p>
    {% endif %}
</div>

{% include 'store/footer.html' %}

<script>
    function updateQuantity(button, delta) {
        const input = button.parentElement.querySelector('input[name="quantity"]');
        const newValue = parseInt(input.value) + delta;
        if (newValue >= 1) {
            input.value = newValue;
        }
    }

    // Remove arrows from number input
    document.querySelectorAll('.no-arrows').forEach(input => {
        input.addEventListener('keydown', (e) => {
            if (e.key === 'ArrowUp' || e.key === 'ArrowDown') {
                e.preventDefault();
            }
        });
    });
</script>

<style>
    /* Remove arrows from number input */
    input[type="number"]::-webkit-outer-spin-button,
    input[type="number"]::-webkit-inner-spin-button {
        -webkit-appearance: none;
        margin: 0;
    }

    input[type="number"] {
        -moz-appearance: textfield;
    }
</style>

storefront/store/templates/store/customer_profile.html
{% load static %}
{%include 'store/header_with_cart.html'%}

    <div class="container mx-auto mt-8">
        <div class="flex">
            <!-- Sidebar for Navigation Tabs -->
            <div class="w-1/4">
                <ul class="border-r border-gray-200">
                    <li id="myInfoTab" class="tab block py-2 px-4 hover:bg-gray-100">My Info</li>
                    <li id="myOrdersTab" class="tab block py-2 px-4 hover:bg-gray-100">My Orders</li>
                </ul>
            </div>

            <!-- Main Content Area -->
            <div class="w-3/4 p-4" id="tabContent">
                <main id = "main-content">
                <h1 id = "username"></h1>
              

            </main>
                <!-- Dynamic content will be loaded here based on the active tab -->
            </div>
        </div>
    </div>

    <footer>
        <!-- Your footer -->
    </footer>

    <!-- Your scripts -->
    <script src="{% static 'js/profile_tabs.js' %}"></script>
    <script src="{% static 'js/TokenToGetUser.js' %}"></script>
</body>
</html>

storefront/store/templates/store/footer.html
{% load static %}
<footer class="text-center p-4 text-gray-600 text-sm bg-white w-full">
    <div class="container mx-auto">
        <p>© 2023 MeowMart | Developed by ShaqDevOps</p>
    </div>

    <script src="{% static 'js/CartVisual.js' %}"></script>
    <script src="{% static 'js/CartFunctions.js' %}"></script>
</footer>

storefront/store/templates/store/header_without_cart_without_signin.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ product.title }} - MeowMart</title>
    <link href="{% static 'cart.css' %}" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.1.2/dist/tailwind.min.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;600&display=swap" rel="stylesheet">
    <script src="https://cdn.tailwindcss.com"></script>
    <style>
        .nav-item {
            transition: background-color 0.3s ease, color 0.3s ease;
        }

        .nav-item.active {
            background-color: #d3d3d3;
            color: #a1a1a1;
        }

        .custom-select {
            background-color: #1a202c;
            /* Dark background */
            color: white;
            /* White text */
        }
    </style>
</head>

<body class="bg-gray-100 font-sans leading-normal tracking-normal">
    <header class="bg-white p-2 shadow">
        <div class="container mx-auto flex items-center justify-between">
            <div class="flex items-center space-x-8">
                <!-- Logo -->
                <div class="flex items-center flex-shrink-0">
                    <a href="{% url 'core:Home' %}">
                        <img src="{% static 'logo.png' %}" alt="MeowMart Logo" class="h-16 w-18 md:h-24 md:w-26">
                    </a>
                </div>

                <!-- Navigation Links -->
                <nav class="hidden md:flex space-x-8">
                    <a href="{% url 'store:products_page' %}"
                        class="text-gray-800 hover:text-purple-600 px-3 py-2 rounded-md text-lg font-medium nav-item">Products</a>
                    <a href="{% url 'core:profile' %}"
                        class="text-gray-800 hover:text-purple-600 px-3 py-2 rounded-md text-lg font-medium nav-item">My
                        Account</a>
                </nav>
            </div>

            <!-- Mobile menu button -->
            <div class="md:hidden">
                <button onclick="toggleMobileMenu(event)" class="text-black focus:outline-none">
                    <svg class="h-8 w-8" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24">
                        <path d="M4 6h16M4 12h16m-16 6h16"></path>
                    </svg>
                </button>
            </div>
        </div>

        <!-- MOBILE MENU ELEMENTS -->
        <div id="mobile-menu" class="hidden">
            <a href="{% url 'store:products_page' %}"
                class="block px-3 py-2 rounded-md text-base font-medium text-gray-800 hover:text-purple-600 nav-item">Products</a>
            <a href="{% url 'core:profile' %}"
                class="block px-3 py-2 rounded-md text-base font-medium text-gray-800 hover:text-purple-600 nav-item">My
                Account</a>
        </div>
    </header>
    <script>
        function toggleMobileMenu(event) {
            const mobileMenu = document.getElementById('mobile-menu');
            if (mobileMenu) {
                mobileMenu.classList.toggle('hidden');
            }
        }

        document.querySelectorAll('.nav-item').forEach(item => {
            item.addEventListener('click', function () {
                document.querySelectorAll('.nav-item').forEach(nav => nav.classList.remove('active'));
                this.classList.add('active');
            });
        });
    </script>
</body>

</html>

storefront/store/templates/store/order_form.html
<!-- order_form.html -->
<style>
    .custom-select {
        background-color: #1a202c;
        /* Dark background */
        color: white;
        /* White text */
        border-color: #2d3748;
        /* Border color */
    }

    .custom-select option {
        background-color: #1a202c;
        /* Dark background for options */
        color: white;
        /* White text for options */
    }
</style>

<form method="post" action="{% url 'store:post_order' %}"
    class="bg-white p-8 border border-gray-200 rounded-lg shadow-md">
    {% csrf_token %}
    <div class="mb-4">
        <label for="phone" class="block text-gray-700 text-sm font-bold mb-2">Phone Number:</label>
        <input type="text" id="phone" name="phone"
            class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
            required>
    </div>
    <div class="mb-4">
        <label for="street" class="block text-gray-700 text-sm font-bold mb-2">Street Address:</label>
        <input type="text" id="street" name="street"
            class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
            required>
    </div>
    <div class="mb-4">
        <label for="city" class="block text-gray-700 text-sm font-bold mb-2">City:</label>
        <input type="text" id="city" name="city"
            class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
            required>
    </div>
    <div class="mb-4">
        <label for="state" class="block text-gray-700 text-sm font-bold mb-2">State:</label>
        {{ form.state }}
    </div>
    <input type="hidden" name="cart_id" value="{{ cart.id }}">
    <button type="submit"
        class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline"
        id="submitOrderButton">Place Order</button>
</form>

<script>
    // Wait for the DOM to be fully loaded
    document.addEventListener('DOMContentLoaded', function () {
        // Find the form by its ID
        const orderForm = document.getElementById('orderForm');

        // Attach an event listener to the form submission
        orderForm.addEventListener('submit', function () {
            // Remove 'cart_id' from local storage
            localStorage.removeItem('cart_id');
        });
    });
</script>

storefront/store/templates/store/order_success.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Order Success - MeowMart</title>
</head>
<body>
    {% include 'store/header_without_cart_without_signin.html' %}

    <!-- Container to display order details -->
    <div id="orderDetailsContainer" class="container mx-auto my-10 p-6 bg-white shadow-lg rounded-lg">
        <h2 class="text-3xl font-semibold mb-2 text-center">Thank you for your order!</h2>
        <p id="order_id" class="text-lg text-center">Your order number is <strong>{{ order.id }}</strong>.</p>
        <div class="mt-6">
            <h3 class="text-xl font-semibold mb-4">Order Summary</h3>
            <ul id="orderItemsList">
                {% for item in order.items %}
                    <li class="flex justify-between border-b-2 py-2">
                        <span class="font-semibold">{{ item.product.title }} (x{{ item.quantity }})</span>
                        <span>${{ item.unit_price }}</span>
                    </li>
                {% endfor %}
            </ul>
            <p class="mt-4 text-right font-semibold">Total: $<span id="orderTotal">{{ order.total }}</span></p>
        </div>
        <div class="mt-6 text-center">
            <a href="{% url 'store:products_page' %}" class="px-6 py-2 bg-blue-500 text-white font-bold rounded hover:bg-blue-700 transition duration-300">Continue Shopping</a>
        </div>
    </div>

    {% include 'store/footer.html' %}



    
</body>
</html>