storefront/core/urls.py
from . import views
from rest_framework.routers import DefaultRouter
from rest_framework_simplejwt.views import TokenObtainPairView
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.views.generic import TemplateView


app_name = 'core'

router = DefaultRouter()
router.register('SignUp', views.SignUpViewSet, basename='SignUp')
router.register('user', views.UserViewSet, basename='user')

# URLConf
urlpatterns = [
    path('', TemplateView.as_view(template_name='core/index.html'), name='Home'),
    #     path('signin/', views.SignIn, name='sign-in'),
    # path('profile/', views.my_profile, name='customer-profile')
    path('profile/', views.profile, name='profile'),
    path('profile/my_info/', views.my_info, name='my_info'),
    path('profile/my_orders/', views.my_orders, name='my_orders'),
    path('profile/change_details', views.change_details, name='change_details'),
    path('profile/change_email/', views.change_email, name='change_email'),
    path('profile/confirm_password/',
         views.confirm_password, name='confirm_password'),
    path('change_password/', views.change_password, name='change_password'),
    path('logout/', views.custom_logout, name='logout'),
    path('privacy_policy/', views.privacy_policy, name='privacy_policy'),
    path('accounts/login', views.CustomLoginView.as_view(), name='custom_login')
]

urlpatterns += router.urls

storefront/store/urls.py
from django.urls import path
from rest_framework_nested import routers
from . import views

app_name = 'store'


router = routers.DefaultRouter()
router.register('products', views.ProductViewSet, basename='products')
router.register('collections', views.CollectionViewSet)
router.register('carts', views.CartViewSet)
router.register('customers', views.CustomerViewSet, basename='customers')
router.register('orders', views.OrderViewSet, basename='orders')

products_router = routers.NestedDefaultRouter(
    router, 'products', lookup='product')
products_router.register('reviews', views.ReviewViewSet,
                         basename='product-reviews')
products_router.register(
    'images', views.ProductImageViewSet, basename='product-images')
orders_router = routers.NestedDefaultRouter(router, 'orders', lookup='order')

carts_router = routers.NestedDefaultRouter(router, 'carts', lookup='cart')
carts_router.register('items', views.CartItemViewSet, basename='cart-items')

# urlpatterns =[
#     path('products_page', views.\)
# ]

# URLConf
urlpatterns = router.urls + products_router.urls + carts_router.urls

urlpatterns += [

    path('products/products_page/',
         views.ProductViewSet.as_view({'get': 'products_page'}), name='products_page'),
    path('order_form', views.order_form_view, name='order_form'),
    path('order_success', views.order_success_page, name='order_success'),
    path('my_orders', views.my_orders, name='my_orders'),
    path('post_order', views.post_order, name='post_order'),
    path('search/', views.search, name='search'),
    path('search/suggestions/', views.search_suggestions,
         name='search_suggestions'),
]

storefront/storefront/urls.py
from django.urls import path
from django.http import JsonResponse
from django.contrib import admin
from django.urls import path, include
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static
from drf_yasg.views import get_schema_view
from drf_yasg import openapi
from rest_framework.permissions import AllowAny

schema_view = get_schema_view(
    openapi.Info(
        title="Storefront",
        default_version='v1',
        description="API description",
    ),
    public=True,
    permission_classes=(AllowAny,),
)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('__debug__/', include(debug_toolbar.urls)),
    path('', include('core.urls')),
    path('auth/', include('djoser.urls')),
    path('auth/', include('djoser.urls.jwt')),
    path('store/', include(('store.urls', 'store'), namespace='store')),
    path('swagger/', schema_view.with_ui('swagger',
         cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc',
         cache_timeout=0), name='schema-redoc'),
    path('accounts/', include('allauth.urls')),
    path('captcha/', include('captcha.urls')), 
    path('', include('django_prometheus.urls')),
    path('', include('pages.urls')),




]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

storefront/core/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

# Create your models here.
class User(AbstractUser):
  email = models.EmailField(unique=True)

storefront/core/views.py
# Adjust the import based on your actual model location
from django.shortcuts import render
from decimal import Decimal
from django.contrib.auth import logout as auth_logout
from django.http import HttpResponseRedirect
from django.shortcuts import redirect
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
import logging
import json
import requests
from django.shortcuts import render, redirect
from django.http import JsonResponse, HttpResponse, HttpResponseRedirect
from django.core.mail import send_mail
from django.contrib import messages
from django.contrib.auth import get_user_model, authenticate, login, logout as auth_logout, update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.views import View
from rest_framework.permissions import AllowAny, IsAdminUser, IsAuthenticated
from rest_framework.viewsets import ModelViewSet
from rest_framework.response import Response
from rest_framework.decorators import action, api_view, permission_classes
from rest_framework_simplejwt.tokens import RefreshToken
from allauth.socialaccount.models import SocialAccount
from allauth.account.auth_backends import AuthenticationBackend
from allauth.account.forms import SignupForm
from django.urls import reverse
from .forms import CustomUserCreationForm, CustomLoginForm, UserUpdateForm, ChangeEmailForm
from .serializers import UserCreateSerializer, UserSerializer
from store.models import Customer, Address
from .forms import UserForm, CustomerForm, AddressForm
from store.models import Customer, Address

User = get_user_model()
logger = logging.getLogger('core')

User = get_user_model()


class SignUpViewSet(ModelViewSet):
    serializer_class = UserCreateSerializer

    def get_queryset(self):
        if self.action == 'list':
            return User.objects.none()
        return super().get_queryset()

    def get_permissions(self):
        if self.request.method in ['GET', 'POST']:
            return [AllowAny()]
        else:
            return [IsAdminUser()]

    @action(detail=False, methods=['get', 'post'])
    def SignUpForm(self, request):
        if request.method == 'POST':
            form = CustomUserCreationForm(request.POST)
            if form.is_valid():
                user = form.save(commit=False)
                user.email = form.cleaned_data['email']
                user.save()

                # Specify the backend when logging in the user
                backend = 'allauth.account.auth_backends.AuthenticationBackend'
                user.backend = backend

                login(request, user, backend=backend)
                return redirect('/')
        else:
            form = CustomUserCreationForm()

        return render(request, 'account/signup.html', {'form': form})


class CustomLoginView(View):
    template_name = "account/login.html"

    def get(self, request):
        form = CustomLoginForm()
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = CustomLoginForm(request.POST, request=request)
        if form.is_valid():
            user = form.get_user()
            login(request, user)

            refresh = RefreshToken.for_user(user)
            access_token = str(refresh.access_token)

            response = HttpResponseRedirect(request.GET.get('next') or '/')
            response.set_cookie(
                key='access_token',
                value=access_token,
                httponly=True,
                max_age=3600, 
                samesite='Lax'
            )
            response.set_cookie(
                key='refresh_token',
                value=str(refresh),
                httponly=True,
                max_age=3600 * 24 * 7,
                samesite='Lax'
            )
            return response
        else:
            messages.error(request, 'Invalid username/email or password')
            return render(request, self.template_name, {'form': form})


@permission_classes([AllowAny])
class UserViewSet(ModelViewSet):
    serializer_class = UserSerializer

    def get_permissions(self):
        if self.action == 'me':
            self.permission_classes = [IsAuthenticated]
        else:
            self.permission_classes = [IsAdminUser]
        return super().get_permissions()

    def get_queryset(self):
        user = self.request.user
        if user.is_staff:
            return User.objects.all()
        elif user.is_authenticated:
            return User.objects.filter(id=user.id)

    @action(detail=False, methods=['GET', 'PATCH'])
    def me(self, request):
        if request.method == 'GET':
            serializer = UserSerializer(request.user)
            print(serializer.data)
            return Response(serializer.data)


# @login_required
# def my_profile(request):
#     token = request.COOKIES.get('access_token')
#     if not token:
#         return redirect(f'/accounts/login/?next={request.path}')
#     return render(request, 'core/my_profile.html')


def change_password(request):
    return redirect('/accounts/password/reset/')


logger = logging.getLogger(__name__)


@login_required
def custom_logout(request):
    response = HttpResponseRedirect('/')

    # Delete cookies
    response.delete_cookie('access_token')
    response.delete_cookie('refresh_token')
    response.delete_cookie('sessionid')
    response.delete_cookie('csrftoken')

    try:
        auth_logout(request)

        if SocialAccount.objects.filter(user=request.user).exists():
            return redirect('/accounts/logout/')
    except AttributeError:
        pass
    except Exception as e:
        pass

    return response


def change_details(request):
    user = request.user
    customer, created = Customer.objects.get_or_create(user=user)
    address, created = Address.objects.get_or_create(customer=customer)

    if request.method == 'POST':
        post_data = request.POST.copy()
        # Ensure the email field is populated with the user's current email if not provided
        if 'email' not in post_data:
            post_data['email'] = user.email

        user_form = UserForm(post_data, instance=user)
        customer_form = CustomerForm(request.POST, instance=customer)
        address_form = AddressForm(request.POST, instance=address)

        if user_form.is_valid() and customer_form.is_valid() and address_form.is_valid():
            user_form.save()
            customer_form.save()
            address_form.save()
            return redirect('core:my_info')
    else:
        user_form = UserForm(instance=user)
        customer_form = CustomerForm(instance=customer)
        address_form = AddressForm(instance=address)

    context = {
        'user_form': user_form,
        'customer_form': customer_form,
        'address_form': address_form,
        'user': user,
        'customer': customer,
        'address': address,
    }

    return render(request, 'core/change_details.html', context)


def change_email(request):
    if request.method == 'POST':
        form = ChangeEmailForm(request.POST)
        if form.is_valid():
            request.user.email = form.cleaned_data['email']
            request.user.save()
            return redirect('core:my_info')
    else:
        form = ChangeEmailForm()
        return render(request, 'core/change_email.html', {'form': form})


def confirm_password(request):
    # Default to 'change_details' if no next URL is provided
    next_url = request.GET.get('next', 'change_details')
    if request.method == 'POST':
        password = request.POST.get('password')
        user = authenticate(username=request.user.username, password=password)
        if user:
            # Log the user in after successful authentication
            login(request, user)
            return redirect(next_url)  # Redirect to the next URL
        else:
            return render(request, 'core/confirm_password.html', {'error': 'Incorrect password', 'next': next_url})
    return render(request, 'core/confirm_password.html', {'next': next_url})


@login_required
def profile(request):
    return render(request, 'core/profile.html')


def my_info(request):
    user = request.user
    customer, created = Customer.objects.get_or_create(user=user)
    address, created = Address.objects.get_or_create(customer=customer)

    context = {
        'user': user,
        'customer': customer,
        'address': address,
    }

    return render(request, 'core/my_info.html', context)


def my_orders(request):
    user = request.user

    user_orders = user.customer.order_set.all()
    orders_with_totals = []
    for order in user_orders:
        print(f"Processing Order ID: {order.id}")
        items_with_totals = []
        order_total = 0
        for item in order.items.all():
            total_price = item.quantity * item.unit_price
            order_total += total_price
            items_with_totals.append({
                'product': item.product,
                'quantity': item.quantity,
                'unit_price': item.unit_price,
                'total_price': total_price,
            })
        orders_with_totals.append({
            'order': order,
            'items': items_with_totals,
            'order_total': order_total,
        })
    context = {
        'orders_with_totals': orders_with_totals,
    }

    return render(request, 'core/my_orders.html', context)


# def get_all_orders(request):
#     user = request.user

#     user_orders = user.customer.order_set.all()
#     for order in user_orders:
#         item =  order.items
         


def privacy_policy(request):
    return render(request, 'core/privacy_policy.html')

storefront/core/templates/core/base_profile.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Profile{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body>
    {% include 'store/header_with_tailwinds.html' %}
    <!-- {% include 'core/profile_nav.html' %} -->
    <main>
        {% block content %}
        {% endblock %}
    </main>
    <footer></footer>
    <script src="{% static 'js/profile_tabs.js' %}"></script>
    <script src="{% static 'js/CartFunctions.js' %}"></script>
    <script src="{% static 'js/CartVisual.js' %}"></script>
</body>

</html>

storefront/core/templates/core/change_details.html
{% extends 'core/base_profile.html' %}

{% load static %}
{% block title %}Change Info{% endblock %}

{% block content %}
{% include 'core/profile_nav.html' %}

<style>
    .custom-select {
        background-color: white;
        /* Dark background */
        color: white;
        /* White text */
        border-color: #2d3748;
        /* Border color */
    }

    .custom-select option {
        background-color: #1a202c;
        /* Dark background for options */
        color: white;
        /* White text for options */
    }
</style>

<div class="container mx-auto mt-8 px-4">
    <div class="bg-white p-4 border border-gray-200 rounded-lg shadow-md max-w-2xl mx-auto">
        <h1 class="text-2xl font-semibold mb-6 text-center">Change Info</h1>
        <form method="post" action="{% url 'core:change_details' %}">
            {% csrf_token %}
            <div class="mb-4">
                <label class="block text-gray-700 text-sm font-bold mb-2">First Name:</label>
                <input type="text" name="first_name" value="{{ user.first_name }}"
                    class="px-4 py-3 bg-gray-100 rounded w-full">
            </div>
            <div class="mb-4">
                <label class="block text-gray-700 text-sm font-bold mb-2">Last Name:</label>
                <input type="text" name="last_name" value="{{ user.last_name }}"
                    class="px-4 py-3 bg-gray-100 rounded w-full">
            </div>
            <div class="mb-4">
                <label class="block text-gray-700 text-sm font-bold mb-2">Email:</label>
                <input type="email" name="email" value="{{ user.email }}" disabled
                    class="px-4 py-3 bg-gray-100 rounded w-full">
            </div>
            <div class="mb-4">
                <label class="block text-gray-700 text-sm font-bold mb-2">Phone Number:</label>
                <input type="text" name="phone" value="{{ customer.phone }}"
                    class="px-4 py-3 bg-gray-100 rounded w-full">
            </div>
            <div class="mb-4">
                <label class="block text-gray-700 text-sm font-bold mb-2">Street Address:</label>
                <input type="text" name="street" value="{{ address.street }}"
                    class="px-4 py-3 bg-gray-100 rounded w-full">
            </div>
            <div class="mb-4">
                <label class="block text-gray-700 text-sm font-bold mb-2">City:</label>
                <input type="text" name="city" value="{{ address.city }}" class="px-4 py-3 bg-gray-100 rounded w-full">
            </div>
            <div class="mb-4">
                <label class="block text-gray-700 text-sm font-bold mb-2">State:</label>
                {{ address_form.state }}
            </div>
            <div class="flex justify-center">
                <button type="submit" class="bg-gray-800 hover:bg-gray-700 text-white px-4 py-2 rounded w-full">Update
                    Details</button>
            </div>
        </form>
        <div class="mt-4 flex flex-col sm:flex-row sm:justify-between">
            <a href="{% url 'core:confirm_password' %}?next={% url 'core:change_email' %}"
                class="bg-blue-500 hover:bg-blue-700 text-white px-4 py-2 rounded mb-2 sm:mb-0 sm:mr-2 text-center">
                Change Email
            </a>
            <a href="{% url 'core:change_password' %}"
                class="bg-blue-500 hover:bg-blue-700 text-white px-4 py-2 rounded text-center">Change Password</a>
        </div>
    </div>
</div>
{% endblock %}

storefront/core/templates/core/change_email.html
{% extends 'core/base_profile.html' %}

{% load static %}
{% block title %}Change Email{% endblock %}

{% block content %}
{% include 'core/profile_nav.html' %}

<div class="container mx-auto mt-8 px-4">
    <div class="bg-white p-4 border border-gray-200 rounded-lg shadow-md max-w-2xl mx-auto">
        <h1 class="text-2xl font-semibold mb-6 text-center">Change Email</h1>
        <form method="post" action="{% url 'core:change_email' %}">
            {% csrf_token %}
            <div class="mb-4">
                <label class="block text-gray-700 text-sm font-bold mb-2">New Email:</label>
                <input type="email" name="email" value="{{ form.email.value }}"
                    class="px-4 py-3 bg-gray-100 rounded w-full" required>
            </div>
            <div class="flex justify-center">
                <button type="submit" class="bg-gray-800 hover:bg-gray-700 text-white px-4 py-2 rounded w-full">Change
                    Email</button>
            </div>
        </form>
    </div>
</div>
{% endblock %}

storefront/core/templates/core/change_password.html
{% load static %}

<div class="container mx-auto mt-8 px-4">
    <div class="bg-white p-4 border border-gray-200 rounded-lg shadow-md max-w-2xl mx-auto">
        <h1 class="text-2xl font-semibold mb-6">Change Password</h1>
        <form method="post" action="{% url 'store:change_password' %}">
            {% csrf_token %}
            {{ form.as_p }}
            <div class="flex justify-end">
                <button type="submit" class="bg-blue-500 text-white px-4 py-2 rounded">Change Password</button>
            </div>
        </form>
    </div>
</div>

<script src="{% static 'js/TokenToGetUser.js' %}"></script>

storefront/core/templates/core/confirm_password.html
{% extends 'core/base_profile.html' %}

{% load static %}
{% block title %}Confirm Password{% endblock %}

{% block content %}
{% include 'core/profile_nav.html' %}

<div class="container mx-auto mt-8 px-4">
    <div class="bg-white p-4 border border-gray-200 rounded-lg shadow-md max-w-2xl mx-auto">
        <h1 class="text-2xl font-semibold mb-6 text-center">Confirm Password</h1>
        <form method="post" action="{% url 'core:confirm_password' %}?next={{ next }}">
            {% csrf_token %}
            <div class="mb-4">
                <label class="block text-gray-700 text-sm font-bold mb-2">Password:</label>
                <input type="password" name="password" class="px-4 py-3 bg-gray-100 rounded w-full" required>
            </div>
            <div class="flex justify-center">
                <button type="submit"
                    class="bg-gray-800 hover:bg-gray-700 text-white px-4 py-2 rounded w-full">Confirm</button>
            </div>
            {% if error %}
            <p class="text-red-500 text-center mt-4">{{ error }}</p>
            {% endif %}
        </form>
    </div>
</div>
{% endblock %}

storefront/core/templates/core/index.html
{% load static %}

<style>
    /* Define the background image in a separate style block */
    .background-image {
        background-image: url('{% static "eating.jpg" %}');
    }

    /* Custom styles for the button */
    .shop-button {
        position: absolute;
        top: 50%;
        /* Adjust this value to position the button over the cat's head */
        left: 50%;
        transform: translate(-50%, -50%);
        padding: 2rem 4rem;
        /* Increase padding for larger button */
        background-color: transparent;
        /* Transparent background */
        color: white;
        font-size: 1.75rem;
        /* Increase font size */
        font-weight: bold;
        border: 4px solid white;
        /* Heavy border */
        border-radius: 50px;
        /* Make button rounder */
        box-shadow: 0 8px 16px rgba(0, 0, 0, 0.6);
        /* Heavy shadow */
        transition: background-color 0.3s ease, color 0.3s ease;
    }

    .shop-button:hover {
        background-color: rgba(255, 255, 255, 0.2);
        /* Slightly opaque background on hover */
        color: white;
        /* Keep text color white */
    }

    @media (max-width: 768px) {
        .shop-button {
            font-size: 1.25rem;
            padding: 1.5rem 3rem;
            border-radius: 25px;
            /* Adjust border-radius for mobile */
        }
    }
</style>

<body class="bg-gray-50"> <!-- This sets the default background color -->

    {% include 'store/header_with_tailwinds.html' %}

    <!-- Background Image Placeholder -->
    <div class="relative min-h-screen bg-cover bg-no-repeat bg-center background-image">

        <div class="relative z-10 min-h-screen flex flex-col justify-between">
            <div class="container mx-auto px-6 py-12 text-center">
                <h1 class="text-5xl font-bold text-white mb-6">Welcome to MeowMart</h1>
                <p class="text-xl text-white mb-6">Your one-stop shop for all things feline! Right Here. Right Meow.</p>

                <a href="{% url 'store:products_page' %}" class="shop-button">Shop</a>
            </div>
            <!-- Footer -->
            {% include 'store/footer.html' %}
        </div>
    </div>

</body>

</html>

storefront/core/templates/core/my_info.html
{% extends 'core/base_profile.html' %}

{% load static %}

{% block title %}My Info{% endblock %}

{% block content %}
{% include 'core/profile_nav.html' %}


<div class="container mx-auto mt-8 px-4">
    <div class="bg-white p-4 border border-gray-200 rounded-lg shadow-md max-w-2xl mx-auto">
        <h1 class="text-2xl font-semibold mb-6 text-center">My Info</h1>
        <div class="mb-4">
            <label class="block text-gray-700 text-sm font-bold mb-2">Username:</label>
            <div class="px-4 py-3 bg-gray-100 rounded w-full">
                {{ user.username }}
            </div>
        </div>
        <div class="mb-4">
            <label class="block text-gray-700 text-sm font-bold mb-2">First Name:</label>
            <div class="px-4 py-3 bg-gray-100 rounded w-full">
                {{ user.first_name }}
            </div>
        </div>
        <div class="mb-4">
            <label class="block text-gray-700 text-sm font-bold mb-2">Last Name:</label>
            <div class="px-4 py-3 bg-gray-100 rounded w-full">
                {{ user.last_name }}
            </div>
        </div>
        <div class="mb-4">
            <label class="block text-gray-700 text-sm font-bold mb-2">Email:</label>
            <div class="px-4 py-3 bg-gray-100 rounded w-full">
                {{ user.email }}
            </div>
        </div>
        <div class="mb-4">
            <label class="block text-gray-700 text-sm font-bold mb-2">Phone Number:</label>
            <div class="px-4 py-3 bg-gray-100 rounded w-full">
                {{ customer.phone }}
            </div>
        </div>
        <div class="mb-4">
            <label class="block text-gray-700 text-sm font-bold mb-2">Address:</label>
            <div class="px-4 py-3 bg-gray-100 rounded w-full">
                {{ address.street }}, {{ address.city }}, {{address.state}}
            </div>
        </div>
        <div class="flex justify-center">
            <a href="{% url 'core:change_details' %}" class="w-full">
                <button type="button" class="bg-gray-800 hover:bg-gray-700 text-white px-4 py-2 rounded w-full">
                    Change Info
                </button>
            </a>
        </div>
    </div>
</div>
{% endblock %}

storefront/core/templates/core/my_orders.html
{% extends 'core/base_profile.html' %}

{% load static %}

{% block title %}My Orders{% endblock %}

{% block content %}
{% include 'core/profile_nav.html' %}

<div class="container mx-auto mt-8 px-4">
    <h1 class="text-2xl font-semibold mb-6 text-center">My Orders</h1>
    {% if orders_with_totals %}
    {% for order_with_totals in orders_with_totals %}
    <div class="bg-white p-6 border border-gray-200 rounded-lg shadow-md mb-4">
        <h2 class="text-xl font-semibold text-center">Order Number: {{ order_with_totals.order.id }}</h2>
        <h2 class="text-xl font-semibold text-center mt-2">
            Order placed on: {{ order_with_totals.order.placed_at|date:"F j, Y" }}
        </h2>
        <p class="text-lg text-center text-gray-700 mt-2">Total: ${{ order_with_totals.order_total }}</p>
        <h3 class="text-lg font-semibold mt-6">Items:</h3>
        <ul class="list-disc list-inside">
            {% for item in order_with_totals.items %}
            <li class="flex items-center mb-4 bg-gray-100 p-4 rounded-lg shadow-sm">
                {% with item.product.images.all|first as first_image %}
                {% if first_image %}
                <img src="{{ first_image.image.url }}" alt="{{ item.product.title }}"
                    class="w-16 h-16 object-cover rounded mr-4">
                {% else %}
                <img src="{% static 'default-product-image.jpg' %}" alt="Default Image"
                    class="w-16 h-16 object-cover rounded mr-4">
                {% endif %}
                {% endwith %}
                <div>
                    <a href="{% url 'store:products-detail' item.product.id %}"
                        class="font-semibold text-blue-500 hover:underline">{{ item.product.title }}</a>
                    <p>Quantity: {{ item.quantity }} - Unit Price: ${{ item.unit_price }}</p>
                    <p class="font-semibold">Item Total: ${{ item.total_price|floatformat:2 }}</p>
                </div>
            </li>
            {% endfor %}
        </ul>
    </div>
    {% endfor %}
    {% else %}
    <p class="text-center">No orders found.</p>
    {% endif %}
</div>

{% endblock %}

storefront/core/templates/core/my_profile.html
<!-- {% load static %}
{% include 'store/header_with_tailwinds.html' %}

<div class="container mx-auto mt-8">
    <div class="bg-white p-4 border border-gray-200 rounded-lg shadow-md">
        <ul class="flex border-b">
            <li id="myInfoTab" class="tab py-2 px-4 mr-2 rounded-t hover:bg-gray-100 cursor-pointer">My Info</li>
            <li id="myOrdersTab" class="tab py-2 px-4 mr-2 rounded-t hover:bg-gray-100 cursor-pointer">My Orders</li>
            <li id="signOutTab" class="tab py-2 px-4 rounded-t hover:bg-gray-100 cursor-pointer">Sign Out</li>
        </ul>

        <div class="p-8" id="tabContent">
            <h2 class="text-2xl font-semibold mb-4">Welcome back, {{ request.user.first_name }}</h2>
        </div>
    </div>
</div>

<footer></footer>

<script>
    var myOrdersUrl = "{% url 'store:my_orders' %}";
    var myInfoUrl = "{% url 'core:my_info' %}";
    var changePasswordUrl = "{% url 'core:change_password' %}";
    var changeDetailsUrl = "{% url 'core:change_details' %}";
    var signOutUrl = "{% url 'core:logout' %}";
</script>

<script src="{% static 'js/profile_tabs.js' %}"></script>
<script src="{% static 'js/CartFunctions.js' %}"></script>
<script src="{% static 'js/CartVisual.js' %}"></script>
</body>

</html> -->



{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Profile{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body>
    {% include 'store/header_with_tailwinds.html' %}

    <main>
        {% block content %}
        {% endblock %}
    </main>
    <footer></footer>
    <!-- <script src="{% static 'js/profile_tabs.js' %}"></script> -->
    <script src="{% static 'js/CartFunctions.js' %}"></script>
    <script src="{% static 'js/CartVisual.js' %}"></script>
</body>

</html>

storefront/core/templates/core/profile.html
{% extends 'core/base_profile.html' %}

{% block title %}My Profile{% endblock %}

{% block content %}
{% include 'core/profile_nav.html' %}
<div class="container mx-auto mt-8">
    <div class="bg-white p-4 border border-gray-200 rounded-lg shadow-md">
        <div class="p-8" id="tabContent">
            <h2 class="text-3xl font-semibold mb-6 text-center">Welcome back, {{ request.user.first_name }}</h2>
            <p class="text-center text-gray-300">Here you can manage your profile, view your orders, and update your
                personal information.</p>
        </div>
    </div>
</div>
{% endblock %}

storefront/core/templates/core/profile_nav.html
{% load static %}
<nav>
        <ul class="flex justify-center space-x-4 p-4 rounded-t-lg">
                <li class="tab py-2 px-4 rounded-t hover:bg-gray-700 cursor-pointer">
                        <a href="{% url 'core:my_info' %}" class="text-black">My Info</a>
                </li>
                <li class="tab py-2 px-4 rounded-t hover:bg-gray-700 cursor-pointer">
                        <a href="{% url 'core:my_orders' %}" class="text-black">My Orders</a>
                </li>
                <li class="tab py-2 px-4 rounded-t hover:bg-gray-700 cursor-pointer">
                        <a href="{% url 'core:logout' %}" class="text-black">Sign Out</a>
                </li>
        </ul>
</nav>